### PR TITLE
Fix browser update notice

### LINKED ISSUE #138: WALC 0.2.0 redirects to Google Chrome Update after a Whatsapp update today.
I am being shown the Update Google Chrome page after getting a new WhatsApp update notice today. Using the new 0.2.0 appimage on arch linux KDE.

### PR DESCRIPTION
**Pull request by Zzombiee2361**
bug fixes:
- update whatsap-web-electron.js
- make sure whatsapp web is not loaded in dashboard window
- unregister service worker when asked to update browser, fixes #138 
- handle disconnect event and reload whatsapp

### CODE REVIEW

File: src/Main/MainWindow.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ const { Client } = require('whatsapp-web-electron.js');
 // const getPortSync = require('get-port-sync');
 
 const ICON_PATH = path.join(__dirname, '../icons/logo360x360.png');
-const userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36';
+const userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36';
```
Comment (cstayyab) [inline src/Main/MainWindow.js:14]: Will Cause Wrong Keyboard Shortcuts to be displayed by WhatsApp Web
